"""Inline-only, fluid transactional email layout with escaped dynamic content."""

from html import escape
from urllib.parse import urlsplit


def render_html(
    result: dict, language: str, title: str, details: list[str], summary: str, action: str
) -> str:
    french = language == "fr"
    name = escape(" ".join(result["competitor"].split()))
    url = result["url"]
    # Escaping attributes is necessary but does not make unsafe schemes safe.
    parsed = urlsplit(url)
    safe_url = parsed.scheme in {"http", "https"} and bool(parsed.hostname)
    subtitle = (
        "Notification de veille concurrentielle" if french else "Competitor monitoring notification"
    )
    cta = "Voir la page surveillée" if french else "View monitored page"
    footer = (
        "Notification automatique générée par ChangeWatch"
        if french
        else "Automated notification generated by ChangeWatch"
    )
    rows = ""
    for detail in details:
        label, _, value = detail.partition(":")
        emphasis = label.strip() in {"New price", "Nouveau prix"}
        rows += (
            '<tr><td style="padding:5px 0;">'
            f'<div style="font-size:12px;color:#64748b;">{escape(label.strip())}</div>'
            f'<div style="margin-top:2px;font-size:15px;'
            f'font-weight:{700 if emphasis else 400};color:#0f172a;overflow-wrap:anywhere;">'
            f"{escape(value.strip())}</div></td></tr>"
        )
    link = (
        f'<a href="{escape(url, quote=True)}" style="color:#334155;'
        f'text-decoration:underline;font-size:14px;">{cta}</a>'
        if safe_url
        else ""
    )
    return f'''<!doctype html>
<html lang="{"fr" if french else "en"}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ChangeWatch</title></head>
<body style="margin:0;padding:0;background-color:#ffffff;color:#0f172a;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.5;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background-color:#ffffff;"><tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px;text-align:left;">
<tr><td style="padding:0 12px 12px;border-bottom:1px solid #e5e7eb;">
<div style="font-size:16px;font-weight:700;">ChangeWatch</div>
<div style="font-size:14px;color:#64748b;">{subtitle}</div></td></tr>
<tr><td style="padding:16px 12px 8px;">
<div style="overflow-wrap:anywhere;"><strong>{"Concurrent" if french else "Competitor"}:</strong> {name}</div>
<div style="margin-top:6px;"><strong>{"Changement détecté" if french else "Change detected"}:</strong> {escape(title)}</div>
</td></tr>
<tr><td style="padding:0 12px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;"><tr><td style="padding:0 0 12px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;">{rows}</table>
<div style="margin-top:8px;"><strong>Importance:</strong> {escape(str(result["importance_score"]))}/100</div>
</td></tr></table></td></tr>
<tr><td style="padding:12px 12px 0;">
<h2 style="margin:0 0 8px;font-size:16px;">{"Résumé" if french else "Summary"}</h2>
<p style="margin:0;overflow-wrap:anywhere;">{escape(summary)}</p></td></tr>
<tr><td style="padding:16px 12px;">
<h2 style="margin:0 0 8px;font-size:16px;">{"Action recommandée" if french else "Recommended action"}</h2>
<p style="margin:0;overflow-wrap:anywhere;">{escape(action)}</p></td></tr>
<tr><td style="padding:0 12px 16px;">{link}
<p style="margin:12px 0 0;font-size:12px;color:#64748b;overflow-wrap:anywhere;word-break:break-all;">{escape(url)}</p></td></tr>
<tr><td style="padding:20px 12px;border-top:1px solid #e5e7eb;font-size:12px;color:#64748b;">
<div>{"Heure de détection" if french else "Detection time"}: {escape(str(result["detected_at"]))}</div>
<div style="margin-top:8px;">{footer}</div>
</td></tr></table></td></tr></table>
</body></html>'''
