"""Escaped, inline-only multi-event transactional email layout."""

from html import escape
from urllib.parse import urlsplit

from .email_presentation import display_time, event_count


def render_html(
    result: dict,
    language: str,
    title: str,
    details: list[str],
    summary: str,
    action: str,
    *,
    cards: list[dict] | None = None,
    timezone: str = "Europe/Paris",
) -> str:
    french = language == "fr"
    cards = cards or [{"title": title, "entity": "", "details": details, "value": "", "delta": ""}]
    name = escape(" ".join(result["competitor"].split()))
    url = result["url"]
    try:
        parsed = urlsplit(url)
        safe_url = parsed.scheme in {"http", "https"} and bool(parsed.hostname)
    except ValueError:
        safe_url = False
    cta = "Voir la page surveillée" if french else "View monitored page"
    link = (
        f'<a href="{escape(url, quote=True)}" style="color:#334155;text-decoration:underline;font-size:14px;">{cta}</a>'
        if safe_url
        else ""
    )
    blocks = ""
    for card in cards:
        body = ""
        if card.get("entity"):
            body += f'<div style="margin-top:10px;font-weight:600;font-size:16px;overflow-wrap:anywhere;">{escape(str(card["entity"]))}</div>'
        if card.get("value"):
            body += f'<div style="margin-top:8px;font-size:22px;font-weight:600;line-height:1.35;overflow-wrap:anywhere;">{escape(card["value"])}</div>'
            body += f'<div style="margin-top:5px;font-size:14px;color:#475569;">{escape(card["delta"])}</div>'
        else:
            for detail in card["details"]:
                # Entity is already the card heading. URLs remain in the plain fallback.
                if detail.startswith(("Produit:", "Product:", "Page produit:", "Product page:")):
                    continue
                body += f'<div style="margin-top:8px;font-size:14px;overflow-wrap:anywhere;">{escape(str(detail))}</div>'
        blocks += f"""<tr><td style="padding:0 0 10px;">
<table role="presentation" data-event-card="true" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background-color:#f6f7f9;border-radius:8px;"><tr><td style="padding:18px 20px;">
<span style="display:inline-block;font-size:12px;font-weight:600;color:#475569;background-color:#e9edf2;padding:3px 7px;border-radius:4px;">{escape(card["title"])}</span>{body}
</td></tr></table></td></tr>"""
    subtitle = "Veille concurrentielle automatisée" if french else "Automated competitor monitoring"
    footer = (
        "Notification automatique générée par ChangeWatch"
        if french
        else "Automated notification generated by ChangeWatch"
    )
    return f'''<!doctype html>
<html lang="{"fr" if french else "en"}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ChangeWatch</title></head>
<body style="margin:0;padding:0;background-color:#ffffff;color:#17202e;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.55;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;"><tr><td align="center" style="padding:28px 16px;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px;text-align:left;">
<tr><td style="padding:0 0 24px;"><div style="font-size:15px;font-weight:700;">ChangeWatch</div><div style="margin-top:3px;font-size:12px;color:#64748b;">{subtitle}</div></td></tr>
<tr><td style="padding:0 0 18px;"><h1 style="margin:0;font-size:24px;font-weight:600;line-height:1.3;overflow-wrap:anywhere;">{name}</h1><div style="margin-top:8px;font-size:14px;color:#475569;">{event_count(len(cards), french)}</div></td></tr>
{blocks}
<tr><td style="padding:8px 0 18px;font-size:13px;color:#64748b;">{"Importance globale" if french else "Overall importance"}: <span style="color:#334155;font-weight:600;">{escape(str(result["importance_score"]))}/100</span></td></tr>
<tr><td style="padding:0 0 16px;"><h2 style="font-size:13px;margin:0 0 6px;font-weight:700;">{"Résumé" if french else "Summary"}</h2><p style="margin:0;font-size:14px;overflow-wrap:anywhere;">{escape(summary)}</p></td></tr>
<tr><td style="padding:0 0 20px;"><h2 style="font-size:13px;margin:0 0 6px;font-weight:700;">{"Action recommandée" if french else "Recommended action"}</h2><p style="margin:0;font-size:14px;overflow-wrap:anywhere;">{escape(action)}</p></td></tr>
<tr><td style="padding:0 0 24px;">{link}</td></tr>
<tr><td style="padding:16px 0 0;border-top:1px solid #e5e7eb;font-size:11px;color:#64748b;"><div>{"Heure de détection" if french else "Detection time"}: {escape(display_time(result["detected_at"], french, timezone))}</div><div style="margin-top:4px;">{footer}</div></td></tr>
</table></td></tr></table>
</body></html>'''
