"""Per-client seven-day activity windows, evaluated by ordinary Actor runs."""

from datetime import datetime, timedelta, timezone
from html import escape
from zoneinfo import ZoneInfo

from .email_delivery import send_email
from .reliability import digest


def fresh_period(now: datetime) -> dict:
    return {
        "period_start": now.isoformat(),
        "period_end": (now + timedelta(days=7)).isoformat(),
        "checks_count": 0,
        "client_alerts_sent_in_period": 0,
        "urls": {},
        "unsent_qualifying_alerts": 0,
    }


def render_report(period: dict, options: dict) -> tuple[str, str, str]:
    fr = options["language"] == "fr"
    zone = ZoneInfo(options["timezone"])
    start = datetime.fromisoformat(period["period_start"]).astimezone(zone)
    end = (datetime.fromisoformat(period["period_end"]) - timedelta(microseconds=1)).astimezone(
        zone
    )
    dates = f"{start:%d/%m/%Y} – {end:%d/%m/%Y}" if fr else f"{start:%b %d, %Y} – {end:%b %d, %Y}"
    urls = period["urls"]
    healthy = sum(v["status"] == "healthy" for v in urls.values())
    degraded = sum(v["status"] == "degraded" for v in urls.values())
    failing = sum(v["status"] == "failing" for v in urls.values())
    partial = sum(v.get("partial", False) for v in urls.values())
    subject = (
        "[ChangeWatch] Rapport de surveillance hebdomadaire"
        if fr
        else "[ChangeWatch] Weekly monitoring report"
    )
    title = "Rapport de surveillance" if fr else "Monitoring activity report"
    lines = [
        f"{'Période' if fr else 'Period'} : {dates} ({options['timezone']})",
        f"{len(urls)} {'pages surveillées' if fr else 'monitored pages'}",
        f"{period['checks_count']} {'vérifications effectuées (y compris les tentatives en erreur)' if fr else 'checks performed (including failed attempts)'}",
        f"{'Opérationnelles' if fr else 'Healthy'} : {healthy}",
        f"{'Dégradées' if fr else 'Degraded'} : {degraded}",
        f"{'En échec' if fr else 'Failing'} : {failing}",
        f"{period['client_alerts_sent_in_period']} {'alerte significative envoyée' if fr else 'significant alerts sent'}",
    ]
    if degraded or failing or partial:
        lines.append(
            "Certaines pages nécessitent une vérification ; la couverture peut être incomplète."
            if fr
            else "Some pages need review; coverage may be incomplete."
        )
        for url, health in urls.items():
            if health["status"] != "healthy" or health.get("partial"):
                label = (
                    {
                        "healthy": "couverture incomplète",
                        "degraded": "dégradée",
                        "failing": "en échec",
                    }.get(health["status"], health["status"])
                    if fr
                    else (
                        "incomplete coverage"
                        if health.get("partial") and health["status"] == "healthy"
                        else health["status"]
                    )
                )
                lines.append(f"{url} — {label}")
    elif period["unsent_qualifying_alerts"]:
        lines.append(
            "Des alertes n'ont pas pu être envoyées ; leur livraison doit être vérifiée."
            if fr
            else "Some qualifying alerts were not sent; delivery needs review."
        )
    else:
        lines.append(
            "Les dernières vérifications des pages observées ont réussi."
            if fr
            else "The latest checks of the observed pages succeeded."
        )
    lines.append(
        "Des changements mineurs ou non confirmés peuvent avoir été observés. ChangeWatch poursuit la surveillance selon la fréquence convenue."
        if fr
        else "Minor or unconfirmed changes may have been observed. ChangeWatch continues monitoring at the agreed frequency."
    )
    footer = (
        "Notification automatique générée par ChangeWatch"
        if fr
        else "Automated notification generated by ChangeWatch"
    )
    text = "\n\n".join(["ChangeWatch", title, *lines, footer])
    html = f'<!doctype html><html lang="{options["language"]}"><body style="margin:0;background:#ffffff;color:#20242b;font-family:Arial,sans-serif;"><table role="presentation" style="width:100%;max-width:600px;margin:auto;border-collapse:collapse;"><tr><td style="padding:24px;"><p style="font-size:16px;font-weight:bold;">ChangeWatch</p><h1 style="font-size:22px;font-weight:600;">{escape(title)}</h1>'
    html += "".join(
        f'<p style="font-size:14px;line-height:1.6;overflow-wrap:anywhere;">{escape(line)}</p>'
        for line in lines
    )
    html += f'<p style="font-size:12px;color:#68717d;border-top:1px solid #e5e7eb;padding-top:16px;">{escape(footer)}</p></td></tr></table></body></html>'
    return subject, text, html


async def record_activity(
    store,
    client_id: str,
    result: dict,
    options: dict,
    *,
    evaluate=True,
    now: datetime | None = None,
    sender=None,
) -> dict:
    now = now or datetime.now(timezone.utc)
    key = "weekly-" + digest(client_id)
    state = await store.get_value(key)
    if not isinstance(state, dict) or state.get("version") != 1:
        state = {
            "version": 1,
            "client_id": client_id,
            "last_weekly_report_at": None,
            **fresh_period(now),
        }
    if now >= datetime.fromisoformat(state["period_end"]):
        # Keep one frozen pending report for a retry; never fabricate skipped weeks.
        if (
            not state.get("pending")
            and state["checks_count"]
            and not state["client_alerts_sent_in_period"]
        ):
            state["pending"] = {field: state[field] for field in fresh_period(now)}
        state.update(fresh_period(now))
    state["checks_count"] += 1
    state["client_alerts_sent_in_period"] += int(bool(result.get("alert_sent")))
    state["unsent_qualifying_alerts"] += int(
        bool(result.get("alert_triggered") and not result.get("alert_sent"))
    )
    state["urls"][result["url"]] = {
        "status": result.get("monitoring_status", "failing"),
        "partial": result.get("collection_expansion_status")
        in {"partial", "limited", "unsupported", "error"},
    }
    for status in ("healthy", "degraded", "failing"):
        state[status + "_urls"] = [
            url for url, health in state["urls"].items() if health["status"] == status
        ]
    pending = state.get("pending")
    period = pending or state
    last_sent = state.get("last_weekly_report_at")
    cadence_ready = not last_sent or now >= datetime.fromisoformat(last_sent) + timedelta(days=7)
    fields = {
        "weekly_report_eligible": bool(
            evaluate and pending and options["client_email"] and cadence_ready
        ),
        "weekly_report_sent": False,
        "weekly_report_period_start": period["period_start"],
        "weekly_report_period_end": period["period_end"],
        "weekly_report_checks_count": period["checks_count"],
        "weekly_report_alerts_count": period["client_alerts_sent_in_period"],
        "weekly_report_error": None,
    }
    attempted = pending.get("attempted_at") if pending else None
    if attempted and now >= datetime.fromisoformat(attempted) + timedelta(hours=23):
        fields["weekly_report_eligible"] = False
        fields["weekly_report_error"] = (
            "Previous report acceptance is uncertain; operator review required before retry outside the provider idempotency window."
        )
    # Persist counts and pending content before any delivery attempt.
    await store.set_value(key, state)
    if fields["weekly_report_eligible"]:
        subject, text, html = render_report(pending, options)
        # Preserve the first attempt time; retries cannot extend provider deduplication.
        pending.setdefault("attempted_at", now.isoformat())
        await store.set_value(key, state)
        try:
            if sender:
                sent, error = await sender(options["client_email"], subject, text, html)
            else:
                sent, error = await send_email(
                    options["client_email"],
                    subject,
                    text,
                    html,
                    idempotency_key="weekly-" + digest([client_id, pending["period_start"]]),
                )
        except Exception:
            sent, error = False, "Weekly report delivery failed; acceptance is unconfirmed."
        fields.update(weekly_report_sent=sent, weekly_report_error=error)
        if (
            not sent
            and error
            and not any(word in error for word in ("unconfirmed", "unreadable", "HTTP 5"))
        ):
            pending.pop("attempted_at", None)
            await store.set_value(key, state)
        if sent:
            state["last_weekly_report_at"] = now.isoformat()
            state["pending"] = None
            try:
                await store.set_value(key, state)
            except Exception:
                fields["weekly_report_error"] = (
                    "Report accepted, but delivery state could not be persisted; inspect before retrying."
                )
    return fields
